version: '3'
services:
  animewreck_app_server:
    networks:
      - web
    build: ./services/backend/
    image: animewreck
    restart: unless-stopped
    volumes:
      - ./services/backend/model_resources:/animewreck/model_resources
      - ./services/backend/models:/animewreck/models
      - ./services/backend/datasets:/animewreck/datasets
      - ./logs:/animewreck/logs
      - ./services/backend/src:/animewreck/src
      - ./services/backend/src/__init__.py:/animewreck/__init__.py
  animewreck_http_server:
    networks:
      - web
    build: ./services/frontend/
    image: animewreck_frontend_server
    ports:
      - 9000:80
    restart: unless-stopped
    volumes:
      - ./services/web_server/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/usr/share/nginx/logs/
      - ./services/frontend/dist:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-server-animewreck.rule=Host(`animewreck.kshitijkarthick.me`) || Host(`animewreck.kshitij.cc`)"
      - "traefik.http.routers.http-server-animewreck.tls=true"
      - "traefik.http.routers.http-server-animewreck.entrypoints=websecure"
      - "traefik.http.routers.http-server-animewreck.tls.certresolver=myresolver"
networks:
  web:
    external: true
