version: '3'
services:
  app_server:
    build: ./services/backend/
    image: animewreck
    restart: unless-stopped
    volumes:
      - ./services/backend/model_resources:/animewreck/model_resources
      - ./services/backend/models:/animewreck/models
      - ./services/backend/datasets:/animewreck/datasets
      - ./logs:/animewreck/logs
      - ./services/backend/src:/animewreck/src
      - ./services/backend/__init__.py:/animewreck/__init__.py
      - ./services/frontend/dist:/animewreck/dist
  http_server:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./services/web_server/nginx.conf:/etc/nginx/nginx.conf
      - ./services/frontend/dist:/usr/share/nginx/html/
      - ./logs:/usr/share/nginx/logs/