version: '3'
services:
  app_server:
    build: .
    image: animewreck
    restart: unless-stopped
    volumes:
      - ./model_resources:/animewreck/model_resources
      - ./models:/animewreck/models
      - ./datasets:/animewreck/datasets
      - ./logs:/animewreck/logs
      - ./server:/animewreck/server
      - ./__init__.py:/animewreck/__init__.py
      - ./dist:/animewreck/dist
  http_server:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html/
      - ./logs:/usr/share/nginx/logs/